version: "2"

plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-52

exclude_patterns:
- "benchmark/*"
- "build/*"
- "coverage/*"
- "docs/*"
- "examples/*"
- "tasks/*"
- "spec/*"
- "test/*"
- "vendored-minitest/*"
- "**/node_modules/*"
- stdlib/nodejs/js-yaml-3-6-1.js

