# Requires fixing
Metrics/LineLength:
  Enabled: false

# Requires fixing
Lint/AssignmentInCondition:
  Exclude:
    - 'lib/opal/ast/node.rb'
    - 'lib/opal/compiler.rb'
    - 'lib/opal/nodes/helpers.rb'
    - 'lib/opal/nodes/logic.rb'
    - 'lib/opal/nodes/masgn.rb'
    - 'lib/opal/nodes/runtime_helpers.rb'
    - 'lib/opal/nodes/scope.rb'
    - 'lib/opal/nodes/top.rb'
    - 'lib/tilt/opal.rb'
    - 'opal/corelib/comparable.rb'
    - 'opal/corelib/complex.rb'
    - 'opal/corelib/marshal/write_buffer.rb'

# Requires fixing
Style/GuardClause:
  Enabled: false

# Requires fixing
Style/ModuleFunction:
  Exclude:
    - 'lib/opal/config.rb'
    - 'lib/opal/util.rb'
    - 'stdlib/nodejs/fileutils.rb'
    - 'stdlib/js.rb'

# Requires fixing
# TODO: move opal/**/*.rb to .rubocop.yml
# (unreleased version on GH has inherit_mode option)
# after fixing other cases, rubocop doesn't support Exclude section merging.
# Opal doesn't support freezing anyway
Style/MutableConstant:
  Exclude:
    - 'opal/**/*.rb'
    - 'stdlib/**/*.rb'
    - 'lib/opal/nodes/call.rb'
    - 'lib/opal/util.rb'
