inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false
  # Max: 120

Naming/MethodName:
  Exclude:
    - 'opal/**/*.rb' # Ruby has methods like Integer/Float/Array

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  # The following files use comments to show generated ruby code
  Exclude:
    - 'lib/opal/rewriters/binary_operator_assignment.rb'
    - 'lib/opal/rewriters/logical_operator_assignment.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'opal/**/*.rb'

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'opal/**/*.rb'

Style/GlobalVars:
  Exclude:
    - 'opal/corelib/kernel.rb'
