language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx
  - jruby

before_install:
  - git submodule update --init

notifications:
  irc: "irc.freenode.org#opal"

matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
