name: opal
version: 0.3.9
description: Ruby runtime on top of javascript
keywords: [opal, ruby, javascript, runtime]

directories:
  lib: "./lib"

bin:
  opal: "./bin/opal"

dev_dependencies:
  therubyracer: 0.9.4
  otest: "git://github.com/adambeynon/otest.git"

